import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/visaoffers" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Visaoffers
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/visadetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Visadetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/countries" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Countries
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/countrydetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Countrydetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blog" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Blog
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blogdetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Blogdetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/team" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Team
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/teamdetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Teamdetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/faq" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FAQ
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contact" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Contact
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/error" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Error
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/storydetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Storydetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/gallery" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Gallery
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/visa" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Visa
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/pricingtables" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Pricingtables
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/coaching" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Coaching
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/successstory" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Successstory
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/about" style={{ color: "#87CEFA", textDecoration: "none" }}>
            About
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
